# Travis CI Configuration
# https://docs.travis-ci.com
# This file is based on
# TravisCI · koalaman/shellcheck Wiki
# https://github.com/koalaman/shellcheck/wiki/TravisCI
language: gitignore

## Use container-based infrastructure for quicker build start-up
sudo: false

## We only support Ubuntu 14.04 and newer
dist: trusty

addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck
    - realpath      # Merged to GNU Coreutils in Ubuntu 16.04

git:
  depth: 30

script:
#- git ls-files -z \*.bash | xargs --max-args=1 --verbose --null -- shellcheck
# The following command will be dropped in favor with the above one after Travis CI environment contains ShellCheck >=0.4.5, which fixes the bug that triggers SC2148 even when `shell` directive is used
- git ls-files -z \*.bash | xargs --max-args=1 --verbose --null -- shellcheck --shell=bash
- ./build.bash

deploy:
  provider: releases
  api_key:
    secure: B50KRoDyZaN69Nb1Tc98f9aOxMywx7p9os1wqvWDcJ1L2oJ/thObJHKaMrhtmWBbcf3TbznJApkbVECHXEB11V7AKQ6z5pJIYu/n9Va2Dacw04GedwNjt4LXxRQv0jJoL/mgScGKMxxF/E4DWrpDdfDJoNVat4BJXaHnLRhkP/fPf8C8QHiObv2G9wC6rPp6EI17CCzl+8sbybDd4GP+PEZYvhHBfnhXRPKxIqa+H9BaBLsHa2umHnKOZj6iK7MXwk4f0370MxwDgd0ussNc0/BltSg9bNGPvVucR46/8rcsvoampUm4lsyzNTUwCBpJ+l0clJTWb18IAfo1idvVx/TD9t+M5zM3PZSf/QQve1kP25BrW9r0fhIZ5/iUE/Mw8sP++MegWJaVufsbm7Gu6MvN+Niy/wOP8MaKLkOhXZHDso+qNo8PdspDft5g3ow8rUHI3tise6Y8PFJFNgTUXwvw3n4LQQaJZjVzW941dglweCodjWco44GkDGie2RXwXd534433rUDQS9D5FAg1xVUb05Z8blBe+mvtzKJqWn728EdsSux1oMkayhTslxSCoC33gF3YPC5EMD6+RtGTH1WBUnHx4HnudNCAO4yF/ADnjs584Ovq9/Ywj4LrpDnaBP7162Y1h5c+oI+lbmqcx0nsMPxThGKQ3KRI2P684v0=
  file_glob: true
  skip_cleanup: true
  file: Software Releases/*.tar.bz2
  on:
    tags: true
